apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: vault-a 
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: sec-a
  data:
  - secretKey: password
    remoteRef:
      key: hpe/ctgasr-dse-developer/prod/argo
      property: token
  - secretKey: username
    remoteRef:
      key: hpe/ctgasr-dse-developer/prod/argo
      property: username
