apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: vault-example 
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: mohamed-newsecret
  data:
  - secretKey: argo
    remoteRef:
      key: hpe/ctgasr-dse-developer/prod/argo
      property: token
