apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-tst1
  namespace: jenkins-staging
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret-a
    template:
      metadata:
        labels:
          "jenkins.io/credentials-type": "usernamePassword"
        annotations:
          "jenkins.io/credentials-description": "test credentials from Kubernetes"
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  data:
    - secretKey: username
      remoteRef:
        key: hpe/ctgasr-dse-developer/prod/mougins
        property: username
    - secretKey: password
      remoteRef:
        key: hpe/ctgasr-dse-developer/prod/mougins
        property: password

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-tst2
  namespace: jenkins-staging
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name:  test-secret-b
    template:
      metadata:
        labels:
          "jenkins.io/credentials-type": "usernamePassword"
        annotations:
          "jenkins.io/credentials-description": "test credentials from Kubernetes"
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  data:
    - secretKey: username
      remoteRef:
        key: hpe/ctgasr-dse-developer/prod/nice
        property: username
    - secretKey: password
      remoteRef:
        key: hpe/ctgasr-dse-developer/prod/nice
        property: token

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-tst3
  namespace: jenkins-staging
spec:
  refreshInterval: "15s"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: test-secret-c
    template:
      metadata:
        labels:
          "jenkins.io/credentials-type": "usernamePassword"
        annotations:
          "jenkins.io/credentials-description": "test credentials from Kubernetes"
      data:
        username: "{{ .username | toString }}"
        password: "{{ .password | toString }}"
  data:
    - secretKey: username
      remoteRef:
        key: hpe/ctgasr-dse-developer/prod/argo
        property: username
    - secretKey: password
      remoteRef:
        key: hpe/ctgasr-dse-developer/prod/argo
        property: token
